//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMCCalculator.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMCCalculator.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the height..
        /// </summary>
        public static string ALERT_PLEASE_ENTER_HEIGHT {
            get {
                return ResourceManager.GetString("ALERT_PLEASE_ENTER_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the weight..
        /// </summary>
        public static string ALERT_PLEASE_ENTER_WEIGHT {
            get {
                return ResourceManager.GetString("ALERT_PLEASE_ENTER_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill all the fields..
        /// </summary>
        public static string ALERT_PLEASE_FILL_ALL_FIELDS {
            get {
                return ResourceManager.GetString("ALERT_PLEASE_FILL_ALL_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate.
        /// </summary>
        public static string Btn_Calculate {
            get {
                return ResourceManager.GetString("Btn_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height.
        /// </summary>
        public static string Entry_Height {
            get {
                return ResourceManager.GetString("Entry_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMC.
        /// </summary>
        public static string Entry_IMC {
            get {
                return ResourceManager.GetString("Entry_IMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        public static string Entry_Weight {
            get {
                return ResourceManager.GetString("Entry_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate your IMC.
        /// </summary>
        public static string Lbl_Calculate_Your_IMC {
            get {
                return ResourceManager.GetString("Lbl_Calculate_Your_IMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your weight is low..
        /// </summary>
        public static string RESULT_LOW_WEIGHT {
            get {
                return ResourceManager.GetString("RESULT_LOW_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your weight is normal..
        /// </summary>
        public static string RESULT_NORMAL_WEIGHT {
            get {
                return ResourceManager.GetString("RESULT_NORMAL_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have obesity..
        /// </summary>
        public static string RESULT_OBESITY_WEIGHT {
            get {
                return ResourceManager.GetString("RESULT_OBESITY_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have overweight..
        /// </summary>
        public static string RESULT_OVER_WEIGHT {
            get {
                return ResourceManager.GetString("RESULT_OVER_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        public static string Title_Alert {
            get {
                return ResourceManager.GetString("Title_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result.
        /// </summary>
        public static string Title_Result {
            get {
                return ResourceManager.GetString("Title_Result", resourceCulture);
            }
        }
    }
}
